### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by PaulOckenden** [paulocode/multimesh#25]
Sorry for raising an issue - didn't know how else to contact you. Just wanted to say it's brilliant that you're creating a new client. The three 'official' clients (Android, Apple and Web) are all so very different. Actually four I guess if you include the Python CLI. Each has strengths in particular areas, but also many weaknesses. The Apple client is probably the most feature rich but it's limited to Bluetooth. The Android app is OK, but can't do some things the Apple app can. And as for the web client... well... less said the better.

So I just wanted to show some encouragement for your project. I think there's real scope for a good multi-platform Meshtastic client! 

Good luck with the project. Oh, and sorry for raising an issue!

**Comment by paulocode** [comment]
Thanks! I'm on the Meshtastic discord server.
