### ISSUE TITLE
Feature Request: hops away to the destination node

### ISSUE THREAD

**Issue by francisuk1989** [paulocode/multimesh#29]
@paulocode
I would like to see a feature that tells you how many hops it takes from your node to the destination node.

**Comment by paulocode** [comment]
Thank you for creating an issue. I will look into this.

**Comment by paulocode** [comment]
> No expert here but... I think hops to destination and traceroute, although related, aren't the same thing. I think hops to is the difference between hop_start and hop_limit in the received packet.

You're right! I did not know of this functionality as it is on 2.3.x firmwares. When I made traceroute, I was still on 2.2.x. Reopening this ticket.

**Comment by francisuk1989** [comment]
After fiddling around for the past few days, I've finally worked out how to get the data. I'll tidy everything up and make UI elements for it. 
![image](https://github.com/meshtastic/Meshtastic-Android/assets/7864598/f6c4c57e-ff96-4b63-89e9-1ece7c1ff3fe)

_Originally posted by @DayleDrinkwater in https://github.com/meshtastic/Meshtastic-Android/issues/922#issuecomment-2046159998_

**Comment by paulocode** [comment]
Implemented as of v0.2.0
