### ISSUE TITLE
Feature Request: telemetry data (temp, humidity, pressure)

### ISSUE THREAD

**Issue by francisuk1989** [paulocode/multimesh#30]
@paulocode
1st i would like to see the telemetry data such as temp, humidity and pressure from a node https://meshtastic.org/docs/configuration/module/telemetry/

2nd also having a logo for different types of temp, so for example

-8c - 15c  cold logo
16-20c warm logo
21c + hot logo

2nd is just an idea.

**Comment by paulocode** [comment]
Thank you for creating an issue. I will look into this.

**Comment by paulocode** [comment]
Meshtastic LLC has reimbursed my purchase of telemetry modules, they should arrive within the week.

**Comment by paulocode** [comment]
Implemented as of v0.2.1. If there are issues worth tracking, this will be reopened.
