### ISSUE TITLE
iOS connection by IP continually reconnects

### ISSUE THREAD

**Issue by PaulOckenden** [paulocode/multimesh#34]
0.17 running on iPad Pro 12.9 4th gen, latest iOS.

App connects to Bluetooth nodes fine, but trying to connect via IP to a node running firmware 2.3.4 the app starts to download config from the node, then disconnects and reconnects. Constant looping, every second or so.

Shout if you need any further info.

**Comment by paulocode** [comment]
Hi! please check if something else is connecting to the node. When a node receives a new connection, it drops the old one. My nodes are still on 2.2.x, i'll update and get back to this.

**Comment by PaulOckenden** [comment]
Ah, good shout. I still had an IP connection active from the Android app. Disabled that and MM connects fine. Thank you.
