### ISSUE TITLE
Bug: Group Date in Message View

### ISSUE THREAD

**Issue by fti7** [paulocode/multimesh#37]
Just a Minor UI Issue
Only add the Divider with Date when there is really a new Date. Not each Time if someone else responded
(In an Channel with a lot of Messages, this just takes a lot of space)

![image](https://github.com/paulocode/multimesh/assets/7014664/bcacb5f7-ac15-4308-955d-95268211f202)

**Comment by paulocode** [comment]
Thanks for reporting this. You're correct, the current implementation is wrong. I have not looked at messages in a while, this will be fixed in the next version.

**Comment by paulocode** [comment]
Appears to be fixed by 0805c1e5583dc, for further testing.

**Comment by paulocode** [comment]
resolved as of v0.2.2. iOS version waiting for Apple review.
