### ISSUE TITLE
Testflight Expired

### ISSUE THREAD

**Issue by KN4KNG** [paulocode/multimesh#42]
Testflight project expired, I thought I pulled the decrypted ipa off of my device for side loading, but I did not. 

Can you possibly reload into testflight or provide and ipa? 

If you are able to provide testflight renewal I can pull the ipa and decrypt it for universal sideloading purposes. 

Thank you!

**Comment by paulocode** [comment]
this is done

**Comment by KN4KNG** [comment]
Thank you I've got 0.2.4 decrypted and backed up!
